coverage_service: cobertura_xml
xcodeproj: ./FastSocket.xcodeproj
scheme: FastSocket
source_directory: ./FastSocket
output_directory: ./
ignore:
- "**/Pods/*"
- "thirdparty/*"
- "./Scripts/*"
- "**/3rdParty/*"
- "../**/Developer/*"
- "**/libraries/*"
- "Module-Core/*"
- "Module-Components/*"
- "**/AppUnitTests/*"