env:
  global:
    - CC_TEST_REPORTER_ID=d212e877cf83b527bc6966a88b0a2dbdd37dd25e66af926eaa3887811d9dff9a

# The OSX Image on which the build should be testet
osx_image: xcode11

# the programming language
language: swift

# install tools before starting
before_install:
  - gem install slather
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-darwin-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

# install fastlane stuff
install:
  - bundle install
  - bundle update fastlane
  
# build
jobs:
  include:
    - stage: build
      script: fastlane build_xcode
    - stage: test
      script: fastlane test_xcode
    - stage: deploy
      script:
        - fastlane archive_generic_ios_xcode
        - fastlane archive_ios_simulator_xcode
        - fastlane build_framework_xcode
    - stage: lint
      script:
        - slather
        - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

# run stages
stages:
  - build
  - test
  - name: deploy
    if: tag IS present
  - name: lint
    if: branch = master
