version: 2
jobs:
  build:
    macos:
      xcode: "10.2.0"
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: build_xcode
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run: bundle install
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE

  test:
    macos:
      xcode: "10.2.0"
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test_xcode
    shell: /bin/bash --login -o pipefail
    steps:
      - checkout
      - run: bundle install
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE

  swiftlint:
    docker:
      - image: dantoml/swiftlint:latest
    steps:
      - checkout
      - run: swiftlint lint --reporter junit | tee result.xml
      - store_artifacts:
          path: result.xml
      - store_test_results:
          path: result.xml
        
workflows:
  version: 2
  build-and-test:
    jobs:
      - swiftlint:
          filters:
            branches:
              only:
                - master
                - develop
      - build:
          filters:
            branches:
              only:
                - master
                - develop
          requires:
            - swiftlint
      - test:
          filters:
            branches:
              only:
                - master
                - develop
          requires:
            - build